'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuNew52WeekHighs() As Boolean
            Get
                Return CType(Me("vTBuNew52WeekHighs"),Boolean)
            End Get
            Set
                Me("vTBuNew52WeekHighs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuStrongVolumeGainers() As Boolean
            Get
                Return CType(Me("vTBuStrongVolumeGainers"),Boolean)
            End Get
            Set
                Me("vTBuStrongVolumeGainers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuBullish50200DayMACrossovers() As Boolean
            Get
                Return CType(Me("vTBuBullish50200DayMACrossovers"),Boolean)
            End Get
            Set
                Me("vTBuBullish50200DayMACrossovers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuBullishMACDCrossovers() As Boolean
            Get
                Return CType(Me("vTBuBullishMACDCrossovers"),Boolean)
            End Get
            Set
                Me("vTBuBullishMACDCrossovers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuOversoldWithAnImprovingRSI() As Boolean
            Get
                Return CType(Me("vTBuOversoldWithAnImprovingRSI"),Boolean)
            End Get
            Set
                Me("vTBuOversoldWithAnImprovingRSI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuMovedAboveUpperBollingerBand() As Boolean
            Get
                Return CType(Me("vTBuMovedAboveUpperBollingerBand"),Boolean)
            End Get
            Set
                Me("vTBuMovedAboveUpperBollingerBand") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuMovedAboveUpperPriceChannel() As Boolean
            Get
                Return CType(Me("vTBuMovedAboveUpperPriceChannel"),Boolean)
            End Get
            Set
                Me("vTBuMovedAboveUpperPriceChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuMovedAboveUpperKeltnerChannel() As Boolean
            Get
                Return CType(Me("vTBuMovedAboveUpperKeltnerChannel"),Boolean)
            End Get
            Set
                Me("vTBuMovedAboveUpperKeltnerChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuImprovingChaikinMoneyFlow() As Boolean
            Get
                Return CType(Me("vTBuImprovingChaikinMoneyFlow"),Boolean)
            End Get
            Set
                Me("vTBuImprovingChaikinMoneyFlow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuNewCCIBuySignals() As Boolean
            Get
                Return CType(Me("vTBuNewCCIBuySignals"),Boolean)
            End Get
            Set
                Me("vTBuNewCCIBuySignals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuParabolicSARBuySignals() As Boolean
            Get
                Return CType(Me("vTBuParabolicSARBuySignals"),Boolean)
            End Get
            Set
                Me("vTBuParabolicSARBuySignals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuStocksInANewUptrendAroon() As Boolean
            Get
                Return CType(Me("vTBuStocksInANewUptrendAroon"),Boolean)
            End Get
            Set
                Me("vTBuStocksInANewUptrendAroon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuStocksInANewUptrendADX() As Boolean
            Get
                Return CType(Me("vTBuStocksInANewUptrendADX"),Boolean)
            End Get
            Set
                Me("vTBuStocksInANewUptrendADX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuGapUps() As Boolean
            Get
                Return CType(Me("vTBuGapUps"),Boolean)
            End Get
            Set
                Me("vTBuGapUps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuBreakawayGapUps() As Boolean
            Get
                Return CType(Me("vTBuBreakawayGapUps"),Boolean)
            End Get
            Set
                Me("vTBuBreakawayGapUps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuRunawayGapUps() As Boolean
            Get
                Return CType(Me("vTBuRunawayGapUps"),Boolean)
            End Get
            Set
                Me("vTBuRunawayGapUps") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBuIslandBottoms() As Boolean
            Get
                Return CType(Me("vTBuIslandBottoms"),Boolean)
            End Get
            Set
                Me("vTBuIslandBottoms") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeNew52WeekLows() As Boolean
            Get
                Return CType(Me("vTBeNew52WeekLows"),Boolean)
            End Get
            Set
                Me("vTBeNew52WeekLows") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeStrongVolumeDecliners() As Boolean
            Get
                Return CType(Me("vTBeStrongVolumeDecliners"),Boolean)
            End Get
            Set
                Me("vTBeStrongVolumeDecliners") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeBearish50200DayMACrossovers() As Boolean
            Get
                Return CType(Me("vTBeBearish50200DayMACrossovers"),Boolean)
            End Get
            Set
                Me("vTBeBearish50200DayMACrossovers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeBearishMACDCrossovers() As Boolean
            Get
                Return CType(Me("vTBeBearishMACDCrossovers"),Boolean)
            End Get
            Set
                Me("vTBeBearishMACDCrossovers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeOverboughtWithADecliningRSI() As Boolean
            Get
                Return CType(Me("vTBeOverboughtWithADecliningRSI"),Boolean)
            End Get
            Set
                Me("vTBeOverboughtWithADecliningRSI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeMovedBelowLowerBollingerBand() As Boolean
            Get
                Return CType(Me("vTBeMovedBelowLowerBollingerBand"),Boolean)
            End Get
            Set
                Me("vTBeMovedBelowLowerBollingerBand") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeMovedBelowLowerPriceChannel() As Boolean
            Get
                Return CType(Me("vTBeMovedBelowLowerPriceChannel"),Boolean)
            End Get
            Set
                Me("vTBeMovedBelowLowerPriceChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeMovedBelowLowerKeltnerChannel() As Boolean
            Get
                Return CType(Me("vTBeMovedBelowLowerKeltnerChannel"),Boolean)
            End Get
            Set
                Me("vTBeMovedBelowLowerKeltnerChannel") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeDecliningChaikinMoneyFlow() As Boolean
            Get
                Return CType(Me("vTBeDecliningChaikinMoneyFlow"),Boolean)
            End Get
            Set
                Me("vTBeDecliningChaikinMoneyFlow") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeNewCCISellSignals() As Boolean
            Get
                Return CType(Me("vTBeNewCCISellSignals"),Boolean)
            End Get
            Set
                Me("vTBeNewCCISellSignals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeParabolicSARSellSignals() As Boolean
            Get
                Return CType(Me("vTBeParabolicSARSellSignals"),Boolean)
            End Get
            Set
                Me("vTBeParabolicSARSellSignals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeStocksInANewDowntrendAroon() As Boolean
            Get
                Return CType(Me("vTBeStocksInANewDowntrendAroon"),Boolean)
            End Get
            Set
                Me("vTBeStocksInANewDowntrendAroon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeStocksInANewDowntrendADX() As Boolean
            Get
                Return CType(Me("vTBeStocksInANewDowntrendADX"),Boolean)
            End Get
            Set
                Me("vTBeStocksInANewDowntrendADX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeGapDowns() As Boolean
            Get
                Return CType(Me("vTBeGapDowns"),Boolean)
            End Get
            Set
                Me("vTBeGapDowns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeBreakawayGapDowns() As Boolean
            Get
                Return CType(Me("vTBeBreakawayGapDowns"),Boolean)
            End Get
            Set
                Me("vTBeBreakawayGapDowns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeRunawayGapDowns() As Boolean
            Get
                Return CType(Me("vTBeRunawayGapDowns"),Boolean)
            End Get
            Set
                Me("vTBeRunawayGapDowns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vTBeIslandTops() As Boolean
            Get
                Return CType(Me("vTBeIslandTops"),Boolean)
            End Get
            Set
                Me("vTBeIslandTops") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPBullishEngulfing() As Boolean
            Get
                Return CType(Me("vCsPBullishEngulfing"),Boolean)
            End Get
            Set
                Me("vCsPBullishEngulfing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPPiercingLine() As Boolean
            Get
                Return CType(Me("vCsPPiercingLine"),Boolean)
            End Get
            Set
                Me("vCsPPiercingLine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPMorningStar() As Boolean
            Get
                Return CType(Me("vCsPMorningStar"),Boolean)
            End Get
            Set
                Me("vCsPMorningStar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPBullishHarami() As Boolean
            Get
                Return CType(Me("vCsPBullishHarami"),Boolean)
            End Get
            Set
                Me("vCsPBullishHarami") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPThreeWhiteSoldiers() As Boolean
            Get
                Return CType(Me("vCsPThreeWhiteSoldiers"),Boolean)
            End Get
            Set
                Me("vCsPThreeWhiteSoldiers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPBearishEngulfing() As Boolean
            Get
                Return CType(Me("vCsPBearishEngulfing"),Boolean)
            End Get
            Set
                Me("vCsPBearishEngulfing") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPDarkCloudCover() As Boolean
            Get
                Return CType(Me("vCsPDarkCloudCover"),Boolean)
            End Get
            Set
                Me("vCsPDarkCloudCover") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPEveningStar() As Boolean
            Get
                Return CType(Me("vCsPEveningStar"),Boolean)
            End Get
            Set
                Me("vCsPEveningStar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPBearishHarami() As Boolean
            Get
                Return CType(Me("vCsPBearishHarami"),Boolean)
            End Get
            Set
                Me("vCsPBearishHarami") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPThreeBlackCrows() As Boolean
            Get
                Return CType(Me("vCsPThreeBlackCrows"),Boolean)
            End Get
            Set
                Me("vCsPThreeBlackCrows") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPRisingThreeMethods() As Boolean
            Get
                Return CType(Me("vCsPRisingThreeMethods"),Boolean)
            End Get
            Set
                Me("vCsPRisingThreeMethods") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPFallingThreeMethods() As Boolean
            Get
                Return CType(Me("vCsPFallingThreeMethods"),Boolean)
            End Get
            Set
                Me("vCsPFallingThreeMethods") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPDragonflyDoji() As Boolean
            Get
                Return CType(Me("vCsPDragonflyDoji"),Boolean)
            End Get
            Set
                Me("vCsPDragonflyDoji") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPGravestoneDoji() As Boolean
            Get
                Return CType(Me("vCsPGravestoneDoji"),Boolean)
            End Get
            Set
                Me("vCsPGravestoneDoji") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPHammer() As Boolean
            Get
                Return CType(Me("vCsPHammer"),Boolean)
            End Get
            Set
                Me("vCsPHammer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPShootingStar() As Boolean
            Get
                Return CType(Me("vCsPShootingStar"),Boolean)
            End Get
            Set
                Me("vCsPShootingStar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPFilledBlackCandles() As Boolean
            Get
                Return CType(Me("vCsPFilledBlackCandles"),Boolean)
            End Get
            Set
                Me("vCsPFilledBlackCandles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPHollowRedCandles() As Boolean
            Get
                Return CType(Me("vCsPHollowRedCandles"),Boolean)
            End Get
            Set
                Me("vCsPHollowRedCandles") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPElderBarTurnedRed() As Boolean
            Get
                Return CType(Me("vCsPElderBarTurnedRed"),Boolean)
            End Get
            Set
                Me("vCsPElderBarTurnedRed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPElderBarTurnedBlue() As Boolean
            Get
                Return CType(Me("vCsPElderBarTurnedBlue"),Boolean)
            End Get
            Set
                Me("vCsPElderBarTurnedBlue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPElderBarTurnedGreen() As Boolean
            Get
                Return CType(Me("vCsPElderBarTurnedGreen"),Boolean)
            End Get
            Set
                Me("vCsPElderBarTurnedGreen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPEnteredIchimokuCloud() As Boolean
            Get
                Return CType(Me("vCsPEnteredIchimokuCloud"),Boolean)
            End Get
            Set
                Me("vCsPEnteredIchimokuCloud") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPMovedAboveIchimokuCloud() As Boolean
            Get
                Return CType(Me("vCsPMovedAboveIchimokuCloud"),Boolean)
            End Get
            Set
                Me("vCsPMovedAboveIchimokuCloud") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPMovedBelowIchimokuCloud() As Boolean
            Get
                Return CType(Me("vCsPMovedBelowIchimokuCloud"),Boolean)
            End Get
            Set
                Me("vCsPMovedBelowIchimokuCloud") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPIchimokuCloudTurnedGreen() As Boolean
            Get
                Return CType(Me("vCsPIchimokuCloudTurnedGreen"),Boolean)
            End Get
            Set
                Me("vCsPIchimokuCloudTurnedGreen") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vCsPIchimokuCloudTurnedRed() As Boolean
            Get
                Return CType(Me("vCsPIchimokuCloudTurnedRed"),Boolean)
            End Get
            Set
                Me("vCsPIchimokuCloudTurnedRed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFTripleTopBreakout() As Boolean
            Get
                Return CType(Me("vPFBuPFTripleTopBreakout"),Boolean)
            End Get
            Set
                Me("vPFBuPFTripleTopBreakout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFSpreadTripleTopBreakout() As Boolean
            Get
                Return CType(Me("vPFBuPFSpreadTripleTopBreakout"),Boolean)
            End Get
            Set
                Me("vPFBuPFSpreadTripleTopBreakout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFAscendingTripleTopBreakout() As Boolean
            Get
                Return CType(Me("vPFBuPFAscendingTripleTopBreakout"),Boolean)
            End Get
            Set
                Me("vPFBuPFAscendingTripleTopBreakout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFQuadrupleTopBreakout() As Boolean
            Get
                Return CType(Me("vPFBuPFQuadrupleTopBreakout"),Boolean)
            End Get
            Set
                Me("vPFBuPFQuadrupleTopBreakout") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFBearishSignalReversal() As Boolean
            Get
                Return CType(Me("vPFBuPFBearishSignalReversal"),Boolean)
            End Get
            Set
                Me("vPFBuPFBearishSignalReversal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFBearTrap() As Boolean
            Get
                Return CType(Me("vPFBuPFBearTrap"),Boolean)
            End Get
            Set
                Me("vPFBuPFBearTrap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFBullishCatapult() As Boolean
            Get
                Return CType(Me("vPFBuPFBullishCatapult"),Boolean)
            End Get
            Set
                Me("vPFBuPFBullishCatapult") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFBullishTriangle() As Boolean
            Get
                Return CType(Me("vPFBuPFBullishTriangle"),Boolean)
            End Get
            Set
                Me("vPFBuPFBullishTriangle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBuPFLowPole() As Boolean
            Get
                Return CType(Me("vPFBuPFLowPole"),Boolean)
            End Get
            Set
                Me("vPFBuPFLowPole") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFTripleBottomBreakdown() As Boolean
            Get
                Return CType(Me("vPFBePFTripleBottomBreakdown"),Boolean)
            End Get
            Set
                Me("vPFBePFTripleBottomBreakdown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFSpreadTripleBottomBreakdown() As Boolean
            Get
                Return CType(Me("vPFBePFSpreadTripleBottomBreakdown"),Boolean)
            End Get
            Set
                Me("vPFBePFSpreadTripleBottomBreakdown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFDescendingTripleBottomBreakdown() As Boolean
            Get
                Return CType(Me("vPFBePFDescendingTripleBottomBreakdown"),Boolean)
            End Get
            Set
                Me("vPFBePFDescendingTripleBottomBreakdown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFQuadrupleBottomBreakdown() As Boolean
            Get
                Return CType(Me("vPFBePFQuadrupleBottomBreakdown"),Boolean)
            End Get
            Set
                Me("vPFBePFQuadrupleBottomBreakdown") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFBullishSignalReversal() As Boolean
            Get
                Return CType(Me("vPFBePFBullishSignalReversal"),Boolean)
            End Get
            Set
                Me("vPFBePFBullishSignalReversal") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFBullTrap() As Boolean
            Get
                Return CType(Me("vPFBePFBullTrap"),Boolean)
            End Get
            Set
                Me("vPFBePFBullTrap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFBearishCatapult() As Boolean
            Get
                Return CType(Me("vPFBePFBearishCatapult"),Boolean)
            End Get
            Set
                Me("vPFBePFBearishCatapult") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFBearishTriangle() As Boolean
            Get
                Return CType(Me("vPFBePFBearishTriangle"),Boolean)
            End Get
            Set
                Me("vPFBePFBearishTriangle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFHighPole() As Boolean
            Get
                Return CType(Me("vPFBePFHighPole"),Boolean)
            End Get
            Set
                Me("vPFBePFHighPole") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property vPFBePFLongTailDown() As Boolean
            Get
                Return CType(Me("vPFBePFLongTailDown"),Boolean)
            End Get
            Set
                Me("vPFBePFLongTailDown") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WindowsApplication1.My.MySettings
            Get
                Return Global.WindowsApplication1.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
